apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
#   annotations:
#     configmanagement.gke.io/cluster-selector: selector-env-anz-x-apps-platint-gke
  labels:
    gatekeeper-policies: v9
    generated: "true"
  name: placmc08v9
spec:
  crd:
    spec:
      names:
        kind: PLACMC08V9
#       validation:
#         openAPIV3Schema:
#           type: object
#           x-kubernetes-preserve-unknown-fields: true
  targets:
  - libs:
    - |-
      package lib.core
     < more rego code >
<end manifest - no more fields after rego code>
