apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PLACMC08V8
metadata:
  name: acmsync
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - configmanagement.gke.io
      kinds:
      - ConfigManagement
  parameters:
    clusterName: cluster-3
    syncBranch: 1.0.0
    syncRepo: https://github.com/jasminewu229/acm-config.git
